services:
  - type: web
    name: xo-coffee
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.1
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: COFFEE_PASSPORT_INTEGRATION_URL
        sync: false
      - key: COFFEE_PASSPORT_INTEGRATION_SECRET
        sync: false
      - key: ADMIN_INTEGRATION_URL
        sync: false
      - key: ADMIN_INTEGRATION_SECRET
        sync: false
